# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Upload pre-built AAB to Google Play"

  lane :deploy do
    upload_to_play_store(
      aab: ENV["AAB_PATH"],
      track: ENV.fetch("PLAY_TRACK", "internal"),
      release_status: "completed",
      version_code: ENV["VERSION_CODE"]
    )
  end
end
