
name: Godot Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Debug
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          echo Building release
          mkdir -p build
          godot --headless --editor res://ci/ci_bootstrap.tscn
          godot --headless --install-android-build-template --export-debug "Android" build/debug.aab

    - name: Build Release
      uses: devcontainers/ci@v0.2
      with:
        runCmd: |
          echo Setting environment variables
          echo ${{ secrets.GODOT_ANDROID_KEYSTORE_BASE64 }} | base64 --decode > release.keystore
          export GODOT_ANDROID_KEYSTORE_RELEASE_PATH=$(pwd)/release.keystore
          export GODOT_ANDROID_KEYSTORE_RELEASE_USER=${{ secrets.GODOT_ANDROID_KEYSTORE_RELEASE_USER }}
          export GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD=${{ secrets.GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD }}
          
          echo Building release
          mkdir -p build
          godot --headless --editor res://ci/ci_bootstrap.tscn
          godot --headless --install-android-build-template --export-release "Android" build/release.aab

    - name: Upload build artifacts
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: AndroidBuild
        path: build/
